### ISSUE TITLE
Version check doesn't work for openjdk 10

### ISSUE THREAD

**Issue by huiser** [antonwierenga/activemq-cli#11] opened 2018-08-02 09:41 UTC
xxxx@xxxx ~ $ /opt/activemq-cli/activemq-cli-0.5.0/bin/activemq-cli

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .

xxxx@xxxx ~ $ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

**Comment by antonwierenga** [comment] 2018-08-02 18:12
activemq-cli uses the [JavaAppPackaging sbt plugin](https://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/index.html) for generating platform specific launch scripts. I have created a [new issue](https://github.com/sbt/sbt-native-packager/issues/1145) in the git repo of this plugin. 

Until this is fixed: the plugin documentation states you can skip the java version check by providing the option -no-version-check to the launch script. This might work for you.

Thanks for reporting!

**Comment by antonwierenga** [comment] 2018-08-02 19:05
Apparently the issue is already fixed in a new version of the JavaAppPackaging sbt plugin.

I updated the plugin 9aae9b90f086a1cfae730e4fa67b6fc2cf4a5faf. Scheduled for activemq-cli 0.6.0.

**Closed by antonwierenga** 2018-08-02 19:05 UTC
